-- WhatsApp inbox + downstream idempotency: leases, renewals and fencing.
--
-- The old inbox used an UPDATE guarded by `intentos`. That is an atomic
-- counter, but it is not a lease: a second worker could reclaim a row while
-- the first worker was still alive, and the old worker could later complete
-- the new worker's row. Every state transition below is fenced by both the
-- owner and a fresh token generated by Postgres.

alter table public.wa_evento_pendiente
  add column if not exists lease_token uuid,
  add column if not exists lease_owner text,
  add column if not exists lease_until timestamptz;

create index if not exists wa_evento_pendiente_lease_idx
  on public.wa_evento_pendiente (lease_until, recibido_en)
  where procesado_en is null and intentos < 5;

alter table public.wa_mensaje_procesado
  add column if not exists lease_token uuid,
  add column if not exists lease_owner text,
  add column if not exists lease_until timestamptz;

create index if not exists wa_mensaje_procesado_lease_idx
  on public.wa_mensaje_procesado (lease_until)
  where completado_en is null;

-- Claim one known inbox row. `FOR UPDATE SKIP LOCKED` makes an overlapping
-- webhook and drain worker mutually exclusive without waiting on a long OCR.
create or replace function public.claim_wa_evento_pendiente(
  p_id text,
  p_intentos_esperados integer,
  p_lease_owner text,
  p_lease_seconds integer
) returns table (
  id text,
  evento jsonb,
  intentos integer,
  lease_token uuid,
  lease_owner text,
  lease_until timestamptz,
  recibido_en timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.wa_evento_pendiente%rowtype;
begin
  if nullif(btrim(p_id), '') is null then return; end if;
  if nullif(btrim(p_lease_owner), '') is null then
    raise exception 'wa inbox lease owner is required';
  end if;
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa inbox lease seconds must be between 30 and 900';
  end if;

  select w.* into v_row
    from public.wa_evento_pendiente w
   where w.id = p_id
     and w.procesado_en is null
     and w.intentos < 5
     and (w.lease_until is null or w.lease_until <= clock_timestamp())
     and (p_intentos_esperados is null or w.intentos = p_intentos_esperados)
   for update skip locked;
  if not found then return; end if;

  update public.wa_evento_pendiente
     set intentos = v_row.intentos + 1,
         lease_token = gen_random_uuid(),
         lease_owner = p_lease_owner,
         lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds)
   where public.wa_evento_pendiente.id = v_row.id
   returning * into v_row;

  return query select v_row.id, v_row.evento, v_row.intentos,
                      v_row.lease_token, v_row.lease_owner,
                      v_row.lease_until, v_row.recibido_en;
end;
$$;

-- Claim a batch directly in the database. The selected rows remain locked
-- until their lease fields are written, so two drain invocations cannot claim
-- the same row even when their initial reads happen at the same time.
create or replace function public.claim_wa_evento_pendientes(
  p_limite integer,
  p_lease_owner text,
  p_lease_seconds integer
) returns table (
  id text,
  evento jsonb,
  intentos integer,
  lease_token uuid,
  lease_owner text,
  lease_until timestamptz,
  recibido_en timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_limite < 1 or p_limite > 200 then
    raise exception 'wa inbox batch size must be between 1 and 200';
  end if;
  if nullif(btrim(p_lease_owner), '') is null then
    raise exception 'wa inbox lease owner is required';
  end if;
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa inbox lease seconds must be between 30 and 900';
  end if;

  return query
  with candidatos as (
    select w.id
      from public.wa_evento_pendiente w
     where w.procesado_en is null
       and w.intentos < 5
       and (w.lease_until is null or w.lease_until <= clock_timestamp())
     order by w.recibido_en, w.id
     limit p_limite
     for update skip locked
  ), actualizados as (
    update public.wa_evento_pendiente w
       set intentos = w.intentos + 1,
           lease_token = gen_random_uuid(),
           lease_owner = p_lease_owner,
           lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds)
      from candidatos c
     where w.id = c.id
     returning w.id, w.evento, w.intentos, w.lease_token,
               w.lease_owner, w.lease_until, w.recibido_en
  )
  select a.id, a.evento, a.intentos, a.lease_token,
         a.lease_owner, a.lease_until, a.recibido_en
    from actualizados a;
end;
$$;

create or replace function public.renew_wa_evento_pendiente(
  p_id text,
  p_lease_token uuid,
  p_lease_owner text,
  p_lease_seconds integer
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa inbox lease seconds must be between 30 and 900';
  end if;
  update public.wa_evento_pendiente
     set lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds)
   where id = p_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and procesado_en is null
     and lease_until > clock_timestamp();
  return found;
end;
$$;

create or replace function public.complete_wa_evento_pendiente(
  p_id text,
  p_lease_token uuid,
  p_lease_owner text,
  p_procesado_en timestamptz default null
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.wa_evento_pendiente
     set procesado_en = coalesce(p_procesado_en, clock_timestamp()),
         ultimo_error = null,
         lease_token = null,
         lease_owner = null,
         lease_until = null
   where id = p_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and procesado_en is null;
  return found;
end;
$$;

-- Fenced failure/requeue. A stale worker cannot clear or decrement a newer
-- worker's lease. `p_devolver_intento` is used only when the worker had no
-- budget to start the message and therefore must not consume an attempt.
create or replace function public.fail_wa_evento_pendiente(
  p_id text,
  p_lease_token uuid,
  p_lease_owner text,
  p_error text default null,
  p_devolver_intento boolean default false
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.wa_evento_pendiente
     set intentos = case when p_devolver_intento then greatest(0, intentos - 1) else intentos end,
         ultimo_error = case when p_devolver_intento then null else left(coalesce(p_error, ''), 500) end,
         lease_token = null,
         lease_owner = null,
         lease_until = null
   where id = p_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and procesado_en is null;
  return found;
end;
$$;

-- Downstream message idempotency uses the same fencing semantics. This closes
-- the old gap where a timed-out worker could complete a newer worker's claim.
create or replace function public.claim_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_owner text,
  p_lease_seconds integer
) returns table (
  estado text,
  lease_token uuid,
  lease_owner text,
  lease_until timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_row public.wa_mensaje_procesado%rowtype;
begin
  if nullif(btrim(p_wa_message_id), '') is null then
    return query select 'nuevo'::text, null::uuid, p_lease_owner, null::timestamptz;
    return;
  end if;
  if nullif(btrim(p_lease_owner), '') is null then
    raise exception 'wa message lease owner is required';
  end if;
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa message lease seconds must be between 30 and 900';
  end if;

  insert into public.wa_mensaje_procesado (
    wa_message_id, lease_token, lease_owner, lease_until
  ) values (
    p_wa_message_id, gen_random_uuid(), p_lease_owner,
    clock_timestamp() + make_interval(secs => p_lease_seconds)
  ) on conflict (wa_message_id) do nothing
  returning * into v_row;

  if found then
    return query select 'nuevo'::text, v_row.lease_token,
                        v_row.lease_owner, v_row.lease_until;
    return;
  end if;

  select * into v_row
    from public.wa_mensaje_procesado
   where wa_message_id = p_wa_message_id
   for update skip locked;

  -- Another worker currently holds the row lock. Treat it as in-flight; do
  -- not wait behind a slow OCR/LLM and never invent a duplicate result.
  if not found then
    return query select 'en_curso'::text, null::uuid,
                        null::text, null::timestamptz;
    return;
  end if;

  if v_row.completado_en is not null then
    return query select 'duplicado'::text, null::uuid,
                        v_row.lease_owner, v_row.lease_until;
  elsif v_row.lease_until is null or v_row.lease_until <= clock_timestamp() then
    update public.wa_mensaje_procesado
       set lease_token = gen_random_uuid(),
           lease_owner = p_lease_owner,
           lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds),
           created_at = clock_timestamp()
     where wa_message_id = p_wa_message_id
     returning * into v_row;
    return query select 'nuevo'::text, v_row.lease_token,
                        v_row.lease_owner, v_row.lease_until;
  else
    return query select 'en_curso'::text, null::uuid,
                        v_row.lease_owner, v_row.lease_until;
  end if;
end;
$$;

create or replace function public.complete_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  update public.wa_mensaje_procesado
     set completado_en = coalesce(completado_en, clock_timestamp()),
         lease_token = null,
         lease_owner = null,
         lease_until = null
   where wa_message_id = p_wa_message_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and completado_en is null;
  return found;
end;
$$;

create or replace function public.renew_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text,
  p_lease_seconds integer
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa message lease seconds must be between 30 and 900';
  end if;
  update public.wa_mensaje_procesado
     set lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds)
   where wa_message_id = p_wa_message_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and completado_en is null
     and lease_until > clock_timestamp();
  return found;
end;
$$;

-- Nombre semántico para los fallos; `release_wa_mensaje_procesado` se
-- conserva como alias compatible con el llamador existente.
create or replace function public.fail_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.wa_mensaje_procesado
   where wa_message_id = p_wa_message_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and completado_en is null;
  return found;
end;
$$;

create or replace function public.release_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text
) returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return public.fail_wa_mensaje_procesado(p_wa_message_id, p_lease_token, p_lease_owner);
end;
$$;

-- These are server-only functions. SECURITY DEFINER is intentionally paired
-- with an empty public API surface and an explicit, fixed search_path.
revoke all on function public.claim_wa_evento_pendiente(text, integer, text, integer) from public, anon, authenticated;
revoke all on function public.claim_wa_evento_pendientes(integer, text, integer) from public, anon, authenticated;
revoke all on function public.renew_wa_evento_pendiente(text, uuid, text, integer) from public, anon, authenticated;
revoke all on function public.complete_wa_evento_pendiente(text, uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function public.fail_wa_evento_pendiente(text, uuid, text, text, boolean) from public, anon, authenticated;
revoke all on function public.claim_wa_mensaje_procesado(text, text, integer) from public, anon, authenticated;
revoke all on function public.renew_wa_mensaje_procesado(text, uuid, text, integer) from public, anon, authenticated;
revoke all on function public.complete_wa_mensaje_procesado(text, uuid, text) from public, anon, authenticated;
revoke all on function public.fail_wa_mensaje_procesado(text, uuid, text) from public, anon, authenticated;
revoke all on function public.release_wa_mensaje_procesado(text, uuid, text) from public, anon, authenticated;
grant execute on function public.claim_wa_evento_pendiente(text, integer, text, integer) to service_role;
grant execute on function public.claim_wa_evento_pendientes(integer, text, integer) to service_role;
grant execute on function public.renew_wa_evento_pendiente(text, uuid, text, integer) to service_role;
grant execute on function public.complete_wa_evento_pendiente(text, uuid, text, timestamptz) to service_role;
grant execute on function public.fail_wa_evento_pendiente(text, uuid, text, text, boolean) to service_role;
grant execute on function public.claim_wa_mensaje_procesado(text, text, integer) to service_role;
grant execute on function public.renew_wa_mensaje_procesado(text, uuid, text, integer) to service_role;
grant execute on function public.complete_wa_mensaje_procesado(text, uuid, text) to service_role;
grant execute on function public.fail_wa_mensaje_procesado(text, uuid, text) to service_role;
grant execute on function public.release_wa_mensaje_procesado(text, uuid, text) to service_role;
