-- 0187 · WhatsApp inbox + downstream idempotency: leases, renewals and fencing.
--
-- The old inbox used an UPDATE guarded by `intentos`. That is an atomic
-- counter, but it is not a lease: a second worker could reclaim a row while
-- the first worker was still alive, and the old worker could later complete
-- the new worker's row. Every state transition below is fenced by both the
-- owner and a fresh token generated by Postgres.

-- 0177 already introduced claim_token/claim_owner/lease_expires_at. Reuse
-- that deployed contract instead of creating a second set of lease columns.
drop index if exists public.wa_evento_pendiente_lease_idx;
create index wa_evento_pendiente_lease_idx
  on public.wa_evento_pendiente (lease_expires_at, recibido_en)
  where procesado_en is null and intentos < 5;

-- Eligibility uses PostgreSQL's clock. Application instances may have clock
-- skew; they only receive rows whose lease is actually expired in the DB.
create or replace function public.listar_wa_pendientes(p_limite integer)
returns table (id text, intentos integer, remitente text)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_limite < 1 or p_limite > 200 then
    raise exception 'wa inbox list size must be between 1 and 200';
  end if;
  return query
  select w.id,
         w.intentos,
         coalesce(nullif(w.evento ->> 'from', ''), w.id) as remitente
    from public.wa_evento_pendiente w
   where w.procesado_en is null
     and w.intentos < 5
     and (w.lease_expires_at is null or w.lease_expires_at <= clock_timestamp())
     -- Si A1 del mismo chofer sigue vivo en otra instancia, A2 no debe ni
     -- aparecer como trabajo disponible. El claim repite la invariantes abajo
     -- porque el listado es solo una optimización, no una frontera de verdad.
     and not exists (
       select 1
         from public.wa_evento_pendiente anterior
        where anterior.procesado_en is null
          and anterior.intentos < 5
          and coalesce(nullif(anterior.evento ->> 'from', ''), anterior.id)
              = coalesce(nullif(w.evento ->> 'from', ''), w.id)
          and (anterior.recibido_en, anterior.id) < (w.recibido_en, w.id)
          and anterior.lease_expires_at > clock_timestamp()
     )
   order by w.recibido_en, w.id
   limit p_limite;
end;
$$;

alter table public.wa_mensaje_procesado
  add column if not exists lease_token uuid,
  add column if not exists lease_owner text,
  add column if not exists lease_until timestamptz;

create index if not exists wa_mensaje_procesado_lease_idx
  on public.wa_mensaje_procesado (lease_until)
  where completado_en is null;

-- Keep the 0177 RPC signature so the migration can land before the new code
-- without breaking an in-flight deployment. Its implementation is replaced
-- with a row lock, authoritative database clock, and owner+token fencing.
create or replace function public.reclamar_wa_pendiente(
  p_id text,
  p_intentos integer,
  p_owner text,
  p_lease_seconds integer default 180
) returns table (id text, evento jsonb, intentos integer, claim_token uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.wa_evento_pendiente%rowtype;
  v_token uuid := gen_random_uuid();
begin
  if nullif(btrim(p_id), '') is null then return; end if;
  if nullif(btrim(p_owner), '') is null then
    raise exception 'wa inbox lease owner is required';
  end if;
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa inbox lease seconds must be between 30 and 900';
  end if;

  select w.* into v_row
    from public.wa_evento_pendiente w
   where w.id = p_id
     and w.procesado_en is null
     and w.intentos < 5
     and w.intentos = p_intentos
     and (w.lease_expires_at is null or w.lease_expires_at <= clock_timestamp())
     -- Orden causal por chofer, impuesto en la base. Esto también cubre el
     -- caso en que un caller reclama A2 directamente y A1 no formó parte de
     -- su lote por estar arrendado a otra instancia.
     and not exists (
       select 1
         from public.wa_evento_pendiente anterior
        where anterior.procesado_en is null
          and anterior.intentos < 5
          and coalesce(nullif(anterior.evento ->> 'from', ''), anterior.id)
              = coalesce(nullif(w.evento ->> 'from', ''), w.id)
          and (anterior.recibido_en, anterior.id) < (w.recibido_en, w.id)
     )
   for update skip locked;
  if not found then return; end if;

  return query
  update public.wa_evento_pendiente w
     set intentos = v_row.intentos + 1,
         claim_token = v_token,
         claim_owner = left(p_owner, 100),
         lease_expires_at = clock_timestamp() + make_interval(secs => p_lease_seconds)
   where w.id = v_row.id
   returning w.id, w.evento, w.intentos, w.claim_token;
end;
$$;

create or replace function public.renovar_wa_pendiente(
  p_id text,
  p_claim_token uuid,
  p_owner text,
  p_lease_seconds integer
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa inbox lease seconds must be between 30 and 900';
  end if;
  update public.wa_evento_pendiente
     set lease_expires_at = clock_timestamp() + make_interval(secs => p_lease_seconds)
   where id = p_id
     and claim_token = p_claim_token
     and claim_owner = p_owner
     and procesado_en is null
     and lease_expires_at > clock_timestamp();
  return found;
end;
$$;

create or replace function public.completar_wa_pendiente(
  p_id text,
  p_claim_token uuid,
  p_owner text,
  p_procesado_en timestamptz default null
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.wa_evento_pendiente
     set procesado_en = coalesce(p_procesado_en, clock_timestamp()),
         ultimo_error = null,
         claim_token = null,
         claim_owner = null,
         lease_expires_at = null
   where id = p_id
     and claim_token = p_claim_token
     and claim_owner = p_owner
     and procesado_en is null;
  return found;
end;
$$;

-- Fenced failure/requeue. A stale worker cannot clear or decrement a newer
-- worker's lease. `p_devolver_intento` is used only when the worker had no
-- budget to start the message and therefore must not consume an attempt.
create or replace function public.fallar_wa_pendiente(
  p_id text,
  p_claim_token uuid,
  p_owner text,
  p_error text default null,
  p_devolver_intento boolean default false
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.wa_evento_pendiente
     set intentos = case when p_devolver_intento then greatest(0, intentos - 1) else intentos end,
         ultimo_error = case when p_devolver_intento then null else left(coalesce(p_error, ''), 500) end,
         claim_token = null,
         claim_owner = null,
         lease_expires_at = null
   where id = p_id
     and claim_token = p_claim_token
     and claim_owner = p_owner
     and procesado_en is null;
  return found;
end;
$$;

-- Downstream message idempotency uses the same fencing semantics. This closes
-- the old gap where a timed-out worker could complete a newer worker's claim.
create or replace function public.claim_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_owner text,
  p_lease_seconds integer
) returns table (
  estado text,
  lease_token uuid,
  lease_owner text,
  lease_until timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_row public.wa_mensaje_procesado%rowtype;
begin
  if nullif(btrim(p_wa_message_id), '') is null then
    return query select 'nuevo'::text, null::uuid, p_lease_owner, null::timestamptz;
    return;
  end if;
  if nullif(btrim(p_lease_owner), '') is null then
    raise exception 'wa message lease owner is required';
  end if;
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa message lease seconds must be between 30 and 900';
  end if;

  insert into public.wa_mensaje_procesado (
    wa_message_id, lease_token, lease_owner, lease_until
  ) values (
    p_wa_message_id, gen_random_uuid(), p_lease_owner,
    clock_timestamp() + make_interval(secs => p_lease_seconds)
  ) on conflict (wa_message_id) do nothing
  returning * into v_row;

  if found then
    return query select 'nuevo'::text, v_row.lease_token,
                        v_row.lease_owner, v_row.lease_until;
    return;
  end if;

  select * into v_row
    from public.wa_mensaje_procesado
   where wa_message_id = p_wa_message_id
   for update skip locked;

  -- Another worker currently holds the row lock. Treat it as in-flight; do
  -- not wait behind a slow OCR/LLM and never invent a duplicate result.
  if not found then
    return query select 'en_curso'::text, null::uuid,
                        null::text, null::timestamptz;
    return;
  end if;

  if v_row.completado_en is not null then
    return query select 'duplicado'::text, null::uuid,
                        v_row.lease_owner, v_row.lease_until;
  elsif v_row.lease_until is null or v_row.lease_until <= clock_timestamp() then
    update public.wa_mensaje_procesado
       set lease_token = gen_random_uuid(),
           lease_owner = p_lease_owner,
           lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds),
           created_at = clock_timestamp()
     where wa_message_id = p_wa_message_id
     returning * into v_row;
    return query select 'nuevo'::text, v_row.lease_token,
                        v_row.lease_owner, v_row.lease_until;
  else
    return query select 'en_curso'::text, null::uuid,
                        v_row.lease_owner, v_row.lease_until;
  end if;
end;
$$;

create or replace function public.complete_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.wa_mensaje_procesado
     set completado_en = coalesce(completado_en, clock_timestamp()),
         lease_token = null,
         lease_owner = null,
         lease_until = null
   where wa_message_id = p_wa_message_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and completado_en is null;
  return found;
end;
$$;

create or replace function public.renew_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text,
  p_lease_seconds integer
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_lease_seconds < 30 or p_lease_seconds > 900 then
    raise exception 'wa message lease seconds must be between 30 and 900';
  end if;
  update public.wa_mensaje_procesado
     set lease_until = clock_timestamp() + make_interval(secs => p_lease_seconds)
   where wa_message_id = p_wa_message_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and completado_en is null
     and lease_until > clock_timestamp();
  return found;
end;
$$;

-- Nombre semántico para los fallos; `release_wa_mensaje_procesado` se
-- conserva como alias compatible con el llamador existente.
create or replace function public.fail_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  delete from public.wa_mensaje_procesado
   where wa_message_id = p_wa_message_id
     and lease_token = p_lease_token
     and lease_owner = p_lease_owner
     and completado_en is null;
  return found;
end;
$$;

create or replace function public.release_wa_mensaje_procesado(
  p_wa_message_id text,
  p_lease_token uuid,
  p_lease_owner text
) returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  return public.fail_wa_mensaje_procesado(p_wa_message_id, p_lease_token, p_lease_owner);
end;
$$;

-- These are server-only functions. SECURITY DEFINER is intentionally paired
-- with an empty public API surface and an explicit, fixed search_path.
revoke all on function public.reclamar_wa_pendiente(text, integer, text, integer) from public, anon, authenticated;
revoke all on function public.listar_wa_pendientes(integer) from public, anon, authenticated;
revoke all on function public.renovar_wa_pendiente(text, uuid, text, integer) from public, anon, authenticated;
revoke all on function public.completar_wa_pendiente(text, uuid, text, timestamptz) from public, anon, authenticated;
revoke all on function public.fallar_wa_pendiente(text, uuid, text, text, boolean) from public, anon, authenticated;
revoke all on function public.claim_wa_mensaje_procesado(text, text, integer) from public, anon, authenticated;
revoke all on function public.renew_wa_mensaje_procesado(text, uuid, text, integer) from public, anon, authenticated;
revoke all on function public.complete_wa_mensaje_procesado(text, uuid, text) from public, anon, authenticated;
revoke all on function public.fail_wa_mensaje_procesado(text, uuid, text) from public, anon, authenticated;
revoke all on function public.release_wa_mensaje_procesado(text, uuid, text) from public, anon, authenticated;
grant execute on function public.reclamar_wa_pendiente(text, integer, text, integer) to service_role;
grant execute on function public.listar_wa_pendientes(integer) to service_role;
grant execute on function public.renovar_wa_pendiente(text, uuid, text, integer) to service_role;
grant execute on function public.completar_wa_pendiente(text, uuid, text, timestamptz) to service_role;
grant execute on function public.fallar_wa_pendiente(text, uuid, text, text, boolean) to service_role;
grant execute on function public.claim_wa_mensaje_procesado(text, text, integer) to service_role;
grant execute on function public.renew_wa_mensaje_procesado(text, uuid, text, integer) to service_role;
grant execute on function public.complete_wa_mensaje_procesado(text, uuid, text) to service_role;
grant execute on function public.fail_wa_mensaje_procesado(text, uuid, text) to service_role;
grant execute on function public.release_wa_mensaje_procesado(text, uuid, text) to service_role;
